# Default values for hermes-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

schedule: "10 * * * *"
endpoint: "mock-mock-ns.apps.baremetal-cluster-jg.qe.devcluster.openshift.com"

image:
  repository: ghcr.io/jgomezselles/hermes
  tag: 0.0.4
  pullPolicy: IfNotPresent

script:
  cm: traffic-script-cm

o11y:
  metrics_endpoint: otel-collector.mock-ns.svc.cluster.local:4318/v1/metrics
  traces_endpoint: