apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "hermes.name" . }}-job
  labels:
    app.kubernetes.io/name: {{ include "hermes.name" . }}
    helm.sh/chart: {{ template "hermes.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hermes.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      template:
        spec:
          volumes:
            - name: {{ .Values.global.hermes.cm | default .Values.script.cm }}-volume
              configMap:
                 name: {{ .Values.global.hermes.cm | default .Values.script.cm }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.global.hermes.repo | default .Values.image.repository }}:{{ .Values.global.hermes.tag | default .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
            - hermes
            - -r{{ .Values.global.hermes.rate | default .Values.rate }}
            - -p{{ .Values.global.hermes.print | default .Values.print }}
            - -t{{ .Values.global.hermes.time | default .Values.time }}
            volumeMounts:
            - name: {{ .Values.global.hermes.cm | default .Values.script.cm }}-volume
              mountPath: "/etc/scripts/"
              readOnly: true
            env:          
            - name: "OTLP_METRICS_ENDPOINT"
              value: {{ .Values.global.hermes.metrics_endpoint | default .Values.o11y.metrics_endpoint }}
            - name: "OTLP_TRACES_ENDPOINT"
              value: {{ .Values.global.hermes.traces_endpoint | default .Values.o11y.traces_endpoint }}
          restartPolicy: Never