apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.script.cm }}
  labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  traffic.json: |
    {
      "dns": "{{ .Values.endpoint }}",
      "port": "80",
      "timeout": 6000,
      "ranges": {
        "range_1": {
          "min": 0,
          "max": 999999
        }
      },
      "flow": [
        "post1",
        "post1"
      ],
      "messages": {
        "post1": {
          "method": "POST",
          "url": "url/example/path/id-<range_1>",
          "body": {
            "field1": "id-<range_1>-suffix",
            "field2": "some_stuff",
            "field3": {
              "sub_field1": 0,
              "subfield2": "some_string"
            }
          },
          "response": {
            "code": 200
          }
        }
      }
    }


